# Generated by Django 3.2.7 on 2021-11-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xChangeSkillApp', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
